two_d_mode: true
publish_tf: true

map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: map

odom0: /odom
odom0_config: [false, false, false,   # X, Y, Z position
               false, false, false,   # Roll, Pitch, Yaw orientation
               true,  true,  false,   # X, Y, Z linear velocity
               false, false, true,    # Roll, Pitch, Yaw angular velocity
               false, false, false]   # Linear and angular accelerations (not used)
odom0_relative: false

imu0: /imu
imu0_config: [false, false, false,    # X, Y, Z position
              false, false, true,     # Roll, Pitch, Yaw orientation
              false, false, false,    # X, Y, Z linear velocity
              false, false, false,    # Roll, Pitch, Yaw angular velocity
              false, false, false]    # Linear and angular accelerations (not used)
imu0_relative: true
imu0_remove_gravitational_acceleration: true
